// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJTb9wgUSf94uVDev4jq536iU53iwbCo',
    appId: '1:298918000507:web:fd0ac5c11bc7ccea5defde',
    messagingSenderId: '298918000507',
    projectId: 'hrmproject-b5417',
    authDomain: 'hrmproject-b5417.firebaseapp.com',
    storageBucket: 'hrmproject-b5417.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmSkHzxSn4rNt4VDooDgjIW_KwwCJ6Rig',
    appId: '1:298918000507:android:24c0c20810a861775defde',
    messagingSenderId: '298918000507',
    projectId: 'hrmproject-b5417',
    storageBucket: 'hrmproject-b5417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAceIdvK5TlGLVsNUV133Lmo6sWPGR6RRk',
    appId: '1:298918000507:ios:e8793eb3a278a0375defde',
    messagingSenderId: '298918000507',
    projectId: 'hrmproject-b5417',
    storageBucket: 'hrmproject-b5417.appspot.com',
    iosBundleId: 'com.example.asiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAceIdvK5TlGLVsNUV133Lmo6sWPGR6RRk',
    appId: '1:298918000507:ios:fc6b98d6f56fadc05defde',
    messagingSenderId: '298918000507',
    projectId: 'hrmproject-b5417',
    storageBucket: 'hrmproject-b5417.appspot.com',
    iosBundleId: 'com.example.asiProject.RunnerTests',
  );
}
